CREATE TABLE Dialogs (
	id SERIAL NOT NULL PRIMARY KEY,
	isPrivate BOOLEAN NOT NULL,
	dialogName VARCHAR(100) NOT NULL,
	dialogPhoto VARCHAR(255),
	createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);