CREATE TABLE Photos (
	id SERIAL NOT NULL PRIMARY KEY,
    users_id INT NOT NULL REFERENCES users(id),
    path VARCHAR(350) NOT NULL --255
);

INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=NoHair&accessoriesType=Prescription02&hairColor=Brown&facialHairType=BeardMedium&facialHairColor=Red&clotheType=Overall&clotheColor=Pink&eyeType=EyeRoll&eyebrowType=UpDown&mouthType=Vomit&skinColor=Brown');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairDreads&accessoriesType=Kurt&hairColor=Auburn&facialHairType=MoustacheMagnum&facialHairColor=Platinum&clotheType=Overall&clotheColor=Blue02&eyeType=Close&eyebrowType=RaisedExcited&mouthType=Default&skinColor=Black');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=Hijab&accessoriesType=Sunglasses&hatColor=Blue03&hairColor=Platinum&facialHairType=BeardMagestic&facialHairColor=Platinum&clotheType=CollarSweater&clotheColor=Red&eyeType=Dizzy&eyebrowType=SadConcerned&mouthType=Default&skinColor=Pale');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairFrizzle&accessoriesType=Prescription02&hatColor=Blue01&hairColor=BlondeGolden&facialHairType=BeardMagestic&facialHairColor=BrownDark&clotheType=CollarSweater&clotheColor=PastelOrange&eyeType=Dizzy&eyebrowType=FlatNatural&mouthType=Grimace&skinColor=Yellow');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraight&accessoriesType=Sunglasses&hairColor=SilverGray&facialHairType=BeardMagestic&facialHairColor=Blonde&clotheType=ShirtScoopNeck&clotheColor=Gray02&eyeType=WinkWacky&eyebrowType=SadConcernedNatural&mouthType=Twinkle&skinColor=DarkBrown');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairTheCaesarSidePart&accessoriesType=Round&hairColor=Platinum&facialHairType=Blank&facialHairColor=BrownDark&clotheType=ShirtScoopNeck&clotheColor=Red&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Grimace&skinColor=DarkBrown');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=Hijab&accessoriesType=Kurt&hatColor=PastelGreen&hairColor=Platinum&facialHairType=MoustacheMagnum&clotheType=BlazerSweater&clotheColor=Gray01&eyeType=Side&eyebrowType=UpDown&mouthType=Default&skinColor=Yellow');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairBun&accessoriesType=Kurt&hatColor=PastelRed&hairColor=Blonde&facialHairType=BeardMagestic&facialHairColor=BlondeGolden&clotheType=Overall&clotheColor=PastelGreen&eyeType=Wink&eyebrowType=UpDown&mouthType=Tongue&skinColor=Yellow');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairSides&accessoriesType=Prescription01&hairColor=Auburn&facialHairType=BeardMagestic&facialHairColor=BlondeGolden&clotheType=BlazerShirt&clotheColor=Heather&eyeType=Squint&eyebrowType=UpDownNatural&mouthType=Smile&skinColor=Light');
INSERT INTO Photos (users_id, path) VALUES (1, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairDreads01&accessoriesType=Blank&hairColor=Brown&facialHairType=MoustacheFancy&facialHairColor=Red&clotheType=BlazerSweater&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Black');

INSERT INTO Photos (users_id, path) VALUES (2, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairDreads01&accessoriesType=Prescription02&hairColor=Platinum&facialHairType=MoustacheMagnum&facialHairColor=Blonde&clotheType=Hoodie&clotheColor=PastelBlue&eyeType=Hearts&eyebrowType=RaisedExcited&mouthType=Twinkle&skinColor=Yellow');
INSERT INTO Photos (users_id, path) VALUES (2, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairSides&accessoriesType=Prescription02&hairColor=Blonde&facialHairType=BeardLight&facialHairColor=Black&clotheType=CollarSweater&clotheColor=Heather&eyeType=Side&eyebrowType=FlatNatural&mouthType=Vomit&skinColor=Brown');
INSERT INTO Photos (users_id, path) VALUES (2, 'https://avataaars.io/?avatarStyle=Circle&topType=Hijab&accessoriesType=Round&hatColor=Gray02&hairColor=PastelPink&facialHairType=BeardMagestic&facialHairColor=Platinum&clotheType=BlazerShirt&clotheColor=Red&eyeType=Happy&eyebrowType=Default&mouthType=Grimace&skinColor=Black');
INSERT INTO Photos (users_id, path) VALUES (2, 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraightStrand&accessoriesType=Kurt&hatColor=Blue02&hairColor=PastelPink&facialHairType=BeardLight&facialHairColor=Auburn&clotheType=GraphicShirt&clotheColor=PastelOrange&graphicType=SkullOutline&eyeType=Surprised&eyebrowType=RaisedExcited&mouthType=Smile&skinColor=Black');
INSERT INTO Photos (users_id, path) VALUES (2, 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairShavedSides&accessoriesType=Blank&hairColor=Red&facialHairType=BeardMedium&facialHairColor=BlondeGolden&clotheType=BlazerShirt&clotheColor=Red&graphicType=Skull&eyeType=Surprised&eyebrowType=AngryNatural&mouthType=Concerned&skinColor=Brown');
INSERT INTO Photos (users_id, path) VALUES (2, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Wayfarers&hairColor=Black&facialHairType=BeardMagestic&facialHairColor=BlondeGolden&clotheType=ShirtCrewNeck&clotheColor=PastelBlue&eyeType=Squint&eyebrowType=AngryNatural&mouthType=Disbelief&skinColor=Pale');

INSERT INTO Photos (users_id, path) VALUES (3, 'https://avataaars.io/?avatarStyle=Circle&topType=Eyepatch&accessoriesType=Wayfarers&hairColor=Black&facialHairType=BeardLight&facialHairColor=Blonde&clotheType=GraphicShirt&clotheColor=Gray02&graphicType=Hola&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=Yellow');
INSERT INTO Photos (users_id, path) VALUES (3, 'https://avataaars.io/?avatarStyle=Circle&topType=Hat&accessoriesType=Sunglasses&facialHairType=BeardLight&facialHairColor=Black&clotheType=Overall&clotheColor=PastelGreen&graphicType=Selena&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light');
INSERT INTO Photos (users_id, path) VALUES (3, 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairDreads02&accessoriesType=Prescription01&hairColor=Brown&facialHairType=Blank&facialHairColor=Red&clotheType=Hoodie&clotheColor=Red&eyeType=Happy&eyebrowType=SadConcernedNatural&mouthType=Sad&skinColor=DarkBrown');