CREATE TABLE Posts (
	id SERIAL NOT NULL PRIMARY KEY,
	postHeader VARCHAR(100) NOT NULL,
	postFit TEXT NOT NULL,
	addTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	users_id INT NOT NULL REFERENCES users(id)
);