DROP TABLE users;

create table Users (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	nickname VARCHAR(15) NOT NULL,
	mainPhoto VARCHAR(100),
	status VARCHAR(50),
	userInfo VARCHAR(500)
);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (1, 'kmartello0', 'https://robohash.org/porropraesentiumut.jpg?size=50x50&set=set1', 'cras pellentesque volutpat dui', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (2, 'vmawman1', 'https://robohash.org/idmaioresvoluptas.png?size=50x50&set=set1', 'rutrum nulla tellus', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (3, 'fmarrow2', 'https://robohash.org/repudiandaeutperspiciatis.bmp?size=50x50&set=set1', 'luctus et ultrices', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (4, 'cgrishanov3', 'https://robohash.org/facilisdoloribusaccusamus.bmp?size=50x50&set=set1', 'id nulla ultrices aliquet maecenas', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (5, 'apauleau4', 'https://robohash.org/veniamrerumaut.png?size=50x50&set=set1', 'augue', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (6, 'fbritney5', 'https://robohash.org/autillodebitis.bmp?size=50x50&set=set1', 'luctus et', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (7, 'ckhotler6', null, 'ac nibh fusce', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (8, 'vsparshatt7', null, 'platea dictumst aliquam', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (9, 'gtruelock8', null, 'tincidunt nulla mollis molestie', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (10, 'cellul9', null, 'amet consectetuer adipiscing', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (11, 'ghearnea', null, 'ac lobortis', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (12, 'mgeggieb', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (13, 'mdmitrievc', 'https://robohash.org/doloresestquibusdam.bmp?size=50x50&set=set1', 'mauris ullamcorper purus', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (14, 'lkernermannd', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (15, 'ccabrere', null, 'in quis', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (16, 'dfeveryearf', 'https://robohash.org/earumidvero.png?size=50x50&set=set1', 'est lacinia nisi', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (17, 'cbrickseyg', null, 'pretium', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (18, 'adelicateh', null, 'nulla nisl nunc nisl duis', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (19, 'elechmerei', 'https://robohash.org/delectusquivoluptatem.png?size=50x50&set=set1', 'aenean fermentum donec', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (20, 'ksavinj', null, 'condimentum neque sapien placerat', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (21, 'dtimmermannk', null, 'metus sapien ut', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (22, 'sfolkl', 'https://robohash.org/repudiandaeetnihil.bmp?size=50x50&set=set1', 'posuere cubilia curae duis', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (23, 'sswattonm', 'https://robohash.org/providentdolordolorum.jpg?size=50x50&set=set1', 'posuere cubilia curae donec', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (24, 'hcourtiern', 'https://robohash.org/beataeetfugit.png?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (25, 'tegero', 'https://robohash.org/fugiatsitet.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (26, 'cwoodisonp', null, null, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (27, 'twyllcockq', null, 'in', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (28, 'sloeberr', 'https://robohash.org/doloremqueremanimi.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (29, 'sloiness', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (30, 'dformant', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (31, 'ccattelu', null, 'mi integer', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (32, 'lgysev', null, 'vulputate elementum nullam varius', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (33, 'cmurricanesw', 'https://robohash.org/quibusdamcupiditateillum.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (34, 'jashlinx', 'https://robohash.org/oditnumquamomnis.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (35, 'kbatesy', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (36, 'gchilesz', null, 'massa tempor', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (37, 'gcarillo10', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (38, 'aemtage11', null, 'vel', 'Vivamus tortor.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (39, 'mlyon12', 'https://robohash.org/illumitaquesit.png?size=50x50&set=set1', 'ut blandit non interdum in', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (40, 'rsprankling13', null, 'a ipsum', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (41, 'cdeverick14', null, 'augue quam sollicitudin vitae consectetuer', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (42, 'chavoc15', 'https://robohash.org/architectolaboriosamquis.bmp?size=50x50&set=set1', 'nibh fusce lacus purus aliquet', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (43, 'mbarhims16', 'https://robohash.org/etiureminima.jpg?size=50x50&set=set1', 'mus vivamus', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (44, 'wberresford17', 'https://robohash.org/corporisoditcupiditate.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (45, 'nphilippard18', null, 'interdum mauris non', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (46, 'qbungey19', 'https://robohash.org/quisconsequunturcorporis.jpg?size=50x50&set=set1', 'ac leo', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (47, 'tgipps1a', null, 'in felis', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (48, 'cklimmek1b', null, 'neque', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (49, 'raudibert1c', null, 'non velit nec nisi', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (50, 'tmulheron1d', null, 'platea dictumst maecenas ut', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (51, 'nkeele1e', null, 'ligula sit', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (52, 'lmoreinis1f', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (53, 'cloughney1g', 'https://robohash.org/reprehenderitametvoluptatem.bmp?size=50x50&set=set1', 'tortor', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (54, 'arogge1h', null, 'nec nisi', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (55, 'hstoodley1i', 'https://robohash.org/delenitimagnamsint.bmp?size=50x50&set=set1', null, 'In sagittis dui vel nisl. Duis ac nibh.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (56, 'ncarl1j', 'https://robohash.org/minusipsaad.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (57, 'eleathley1k', 'https://robohash.org/itaqueinexpedita.png?size=50x50&set=set1', 'ac neque duis bibendum', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (58, 'sbirkenshaw1l', 'https://robohash.org/voluptatevelsunt.bmp?size=50x50&set=set1', 'mi', 'Cras non velit nec nisi vulputate nonummy.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (59, 'eportugal1m', 'https://robohash.org/undecumquia.jpg?size=50x50&set=set1', 'turpis adipiscing lorem vitae mattis', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (60, 'gpinock1n', 'https://robohash.org/autemvoluptatemdolor.bmp?size=50x50&set=set1', 'quisque erat eros', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (61, 'mhuebner1o', null, 'rutrum', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (62, 'wlafontaine1p', 'https://robohash.org/aliquamutlaudantium.jpg?size=50x50&set=set1', 'blandit', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (63, 'kambrogioli1q', null, 'ligula', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (64, 'ajakoub1r', 'https://robohash.org/fugitdebitisconsectetur.bmp?size=50x50&set=set1', 'luctus et ultrices posuere', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (65, 'jirvin1s', 'https://robohash.org/molestiasaccusamusillo.bmp?size=50x50&set=set1', 'curae duis faucibus accumsan', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (66, 'aroff1t', 'https://robohash.org/quomolestiasenim.jpg?size=50x50&set=set1', 'non pretium quis', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (67, 'ngaenor1u', 'https://robohash.org/autveropariatur.png?size=50x50&set=set1', 'cum sociis', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (68, 'chamfleet1v', null, 'odio', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (69, 'eshackesby1w', 'https://robohash.org/voluptasreiciendisaut.jpg?size=50x50&set=set1', 'tempus vel pede morbi', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (70, 'vtill1x', 'https://robohash.org/providentdictaquis.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (71, 'asinclar1y', null, 'vestibulum eget vulputate ut ultrices', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (72, 'asexton1z', 'https://robohash.org/etnatusmaxime.jpg?size=50x50&set=set1', null, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (73, 'acastree20', null, 'tortor sollicitudin mi', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (74, 'bwagenen21', 'https://robohash.org/nisisolutamolestiae.png?size=50x50&set=set1', 'viverra', 'Aliquam non mauris. Morbi non lectus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (75, 'afarge22', 'https://robohash.org/eaearumqui.bmp?size=50x50&set=set1', 'ultrices aliquet maecenas leo', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (76, 'flatehouse23', null, 'proin', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (77, 'mtripcony24', 'https://robohash.org/numquamautemenim.bmp?size=50x50&set=set1', 'vestibulum eget', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (78, 'rperview25', 'https://robohash.org/dignissimosassumendanesciunt.png?size=50x50&set=set1', null, 'Quisque ut erat.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (79, 'abuffy26', null, 'potenti in eleifend', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (80, 'tludlow27', 'https://robohash.org/rerumcumquepariatur.bmp?size=50x50&set=set1', 'nam ultrices', 'Etiam faucibus cursus urna. Ut tellus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (81, 'clidierth28', 'https://robohash.org/enimoditunde.jpg?size=50x50&set=set1', 'cubilia curae', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (82, 'ceveriss29', null, 'quisque erat eros viverra', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (83, 'crotter2a', 'https://robohash.org/quiserrorsed.jpg?size=50x50&set=set1', null, 'Nullam varius. Nulla facilisi.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (84, 'tbruno2b', null, 'molestie lorem quisque ut', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (85, 'nkinze2c', 'https://robohash.org/possimusbeataelaborum.jpg?size=50x50&set=set1', 'amet lobortis', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (86, 'hmccrisken2d', 'https://robohash.org/aspernaturnequecupiditate.jpg?size=50x50&set=set1', 'parturient montes nascetur ridiculus', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (87, 'iburridge2e', 'https://robohash.org/quosautsed.png?size=50x50&set=set1', 'maecenas ut', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (88, 'sgiacobelli2f', null, 'consequat dui nec nisi volutpat', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (89, 'hisoldi2g', null, 'nunc viverra dapibus', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (90, 'kfearenside2h', 'https://robohash.org/aliquidnonvoluptatem.bmp?size=50x50&set=set1', null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (91, 'damanger2i', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (92, 'kslany2j', 'https://robohash.org/optiovoluptasdolor.png?size=50x50&set=set1', 'quam fringilla rhoncus mauris enim', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (93, 'dmckee2k', null, 'nullam', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (94, 'mdosdale2l', null, 'fermentum donec ut mauris eget', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (95, 'hramstead2m', 'https://robohash.org/quamquiaquo.jpg?size=50x50&set=set1', 'nibh in quis justo maecenas', 'Praesent blandit.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (96, 'epirt2n', null, 'imperdiet', 'Duis mattis egestas metus.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (97, 'tsibbe2o', null, null, null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (98, 'jhollebon2p', 'https://robohash.org/evenietaliquidquaerat.bmp?size=50x50&set=set1', 'arcu', null);
insert into Users (id, nickname, mainPhoto, status, userInfo) values (99, 'nbaynon2q', null, null, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into Users (id, nickname, mainPhoto, status, userInfo) values (100, 'slopez2r', null, null, null);
