CREATE TABLE Users (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	mainPhoto VARCHAR(255),
	status VARCHAR(100),
	aboutMe TEXT,
	defaultPath VARCHAR(255) NOT NULL
);